[theme]
base = "light"
primaryColor = "#00ACC1"
backgroundColor = "#F4F6F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#212121"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"
